apiVersion: v1
kind: ConfigMap
metadata:
  name: product-catalog-api-config
  namespace: cn-er-dev
  labels:
    app.kubernetes.io/name: product-catalog-api
    environment: dev
data:
  DB_HOST: "10.100.0.3"
  DB_NAME: "productdb"
  DB_USER: "appuser"
  DB_PORT: "5432"
