apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "product-catalog-api.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "product-catalog-api.labels" . | nindent 4 }}
data:
  DB_HOST: {{ .Values.config.dbHost | quote }}
  DB_NAME: {{ .Values.config.dbName | quote }}
  DB_USER: {{ .Values.config.dbUser | quote }}
  DB_PORT: {{ .Values.config.dbPort | quote }}
