apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "product-catalog-api.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: {{ .Values.secret.name }}
    creationPolicy: Owner
  data:
  - secretKey: {{ .Values.secret.key }}
    remoteRef:
      key: cn-er-dev-db-password
      version: "latest"
