apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "product-catalog-api.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.secret.secretStoreName }}
    kind: {{ .Values.secret.secretStoreKind }}
  target:
    name: {{ .Values.secret.name }}
    creationPolicy: Owner
  data:
  - secretKey: {{ .Values.secret.key }}
    remoteRef:
      key: {{ .Values.secret.remoteKey }}
      {{- if .Values.secret.property }}
      property: {{ .Values.secret.property }}
      {{- end }}
      {{- if .Values.secret.version }}
      version: {{ .Values.secret.version | quote }}
      {{- end }}
