apiVersion: v1
kind: Service
metadata:
  name: {{ include "product-catalog-api.fullname" . }}-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "product-catalog-api.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    protocol: TCP
  selector:
    {{- include "product-catalog-api.selectorLabels" . | nindent 4 }}
