apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-cluster-secret-store
spec:
  provider:
    gcpsm:
      projectID: spartan-alcove-450719-n2
      auth:
        workloadIdentity:
          clusterLocation: europe-west3
          clusterName: cn-er-dev-autopilot
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
